"""remove_user_auth_single_tenant

Revision ID: 11ae282f994f
Revises: cddce1197c26
Create Date: 2026-06-15 13:20:38.668349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11ae282f994f'
down_revision: Union[str, None] = 'cddce1197c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop FK dependency before removing users table.
    op.drop_index("ix_applications_user_id", table_name="applications")
    op.drop_constraint("applications_user_id_fkey", "applications", type_="foreignkey")
    op.drop_column("applications", "user_id")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('applications_user_id_fkey', 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_applications_user_id', 'applications', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
