"""initial_schema

Revision ID: cddce1197c26
Revises: 
Create Date: 2026-06-15 12:06:43.215152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddce1197c26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_price_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', 'effective_from', name='uq_model_pricing')
    )
    op.create_index(op.f('ix_model_pricing_model'), 'model_pricing', ['model'], unique=False)
    op.create_index(op.f('ix_model_pricing_provider'), 'model_pricing', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('trace_key', sa.String(length=64), nullable=False),
    sa.Column('upstream_base_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_trace_key'), 'applications', ['trace_key'], unique=True)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('llm_requests',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('feature', sa.String(length=128), nullable=True),
    sa.Column('user_ref', sa.String(length=128), nullable=True),
    sa.Column('prompt_preview', sa.Text(), nullable=True),
    sa.Column('completion_preview', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_requests_application_id_created_at', 'llm_requests', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_llm_requests_model_created_at', 'llm_requests', ['model', 'created_at'], unique=False)
    op.create_index('ix_llm_requests_status_created_at', 'llm_requests', ['status', 'created_at'], unique=False)
    op.create_table('optimization_reports',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('projected_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('lever', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_reports_application_id'), 'optimization_reports', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_reports_application_id'), table_name='optimization_reports')
    op.drop_table('optimization_reports')
    op.drop_index('ix_llm_requests_status_created_at', table_name='llm_requests')
    op.drop_index('ix_llm_requests_model_created_at', table_name='llm_requests')
    op.drop_index('ix_llm_requests_application_id_created_at', table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_trace_key'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_pricing_provider'), table_name='model_pricing')
    op.drop_index(op.f('ix_model_pricing_model'), table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
